---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# hypotheticalTreatmentAccelerations

<!-- badges: start -->
<!-- badges: end -->

This is an implementation of the time-change interventions described in [Hypothetical Treatment Accelerations](https://arxiv.org/abs/2207.07893).

## Installation

You can install this version of hypotheticalTreatmentAccelerations with:

``` r
# install.packages("devtools")
devtools::install_github("harisf/hypotheticalTreatmentAccelerations")
```

## Example

Using simulated data, we demonstrate a simple time-change intervention on a baseline variable.

```{r example}
library(hypotheticalTreatmentAccelerations)

generateData(100)
dataFr <- readRDS("data/sim_data_n100.rds")

# Additive hazard model for observed treatment
faFit <- timereg::aalen(survival::Surv(from, to, to.state == "treat") ~ 
                          1 + X + L, # confounders
                        data = dataFr[atRiskTreat == 1], 
                        id = dataFr[atRiskTreat == 1, id])

# Time-change intervention (on a baseline confounder X)
dataFr[X == 0, thetaFunc := 2]
dataFr[X == 1, thetaFunc := 1]

# Weights following the time-change intervention
frame <- makeContWeights2(faFit, dataFr, plotWeights = F)

# Observed hazard for death
aaObs <- timereg::aalen(survival::Surv(from, to, to.state == "dead") ~ 1, 
                        data = frame)
# Hypothetical hazard for death (using the weights from the time-change intervention)
aaHyp <- timereg::aalen(survival::Surv(from, to, to.state == "dead") ~ 1, 
                        data = frame, weights = frame$W)
```

```{r survival, echo = T}
# Plot
t <- aaHyp$cum[, 1]
sObs <- exp(-aaObs$cum[, 2])
sHyp <- exp(-aaHyp$cum[, 2])

plot(t, sObs, type = "s", ylim = c(0, 1), main = "Survival", ylab = "Prob.")
lines(t, sHyp, type = "s", col = "blue")
legend("bottomright", c("Hypothetical", "Observed"), lty = 1, col = c("blue", "black"))
```
